export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const CREATE_NEW_LOCATION_FETCH = 'CREATE_NEW_LOCATION_FETCH';
export const CREATE_NEW_LOCATION = 'CREATE_NEW_LOCATION';
export const CREATE_NEW_LOCATION_SUCCESS = "CREATE_NEW_LOCATION_SUCCESS";
export const CREATE_NEW_LOCATION_FAILURE = 'CREATE_NEW_LOCATION_FAILURE';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const ON_CHANGE_INPUT = 'ON_CHANGE_INPUT';
